apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-portal
  template:
    metadata:
      labels:
        app: healthcare-portal
    spec:
      containers:
        - name: healthcare-portal
          image: stewiedocker46/healthcare:latest  # Update with the image built and tagged locally
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "mysql+pymysql://admin:qwertyuiop@database-1.ct8686g6i2km.us-west-2.rds.amazonaws.com:3306/healthcare"
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-portal-service
spec:
  type: NodePort
  selector:
    app: healthcare-portal
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007  # You can specify any available NodePort
