apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-portal
  template:
    metadata:
      labels:
        app: healthcare-portal
    spec:
      containers:
        - name: healthcare-portal
          image: your-dockerhub-username/healthcare-portal:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "mysql+pymysql://username:password@rds-endpoint.amazonaws.com/dbname"
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-portal-service
spec:
  type: NodePort
  selector:
    app: healthcare-portal
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
